"""Update Game model

Revision ID: 0b1bd3b106b6
Revises: 797a26e0d7c4
Create Date: 2025-06-10 00:50:42.851107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1bd3b106b6'
down_revision = '797a26e0d7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unity_build', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('is_unity_build')

    # ### end Alembic commands ###
